export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  FORMATEUR: 'FORMATEUR',
  APPRENANT: 'APPRENANT',
} as const;

export const COURSE_STATUS = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  PUBLISHED: 'PUBLISHED',
  OBSOLETE: 'OBSOLETE',
} as const;

export const ENROLLMENT_STATUS = {
  NOT_ENROLLED: 'NOT_ENROLLED',
  ENROLLED: 'ENROLLED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
} as const;

export const USER_STATUS = {
  CREATED: 'CREATED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
  BANNED: 'BANNED',
} as const;
